### PR TITLE
Add GHA build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/gliptak/mailwhale/runs/6088291630

### CODE REVIEW

**Comment by gliptak** [comment]
@muety please review

https://github.com/gliptak/mailwhale/actions/runs/2198689642

**Comment by muety** [comment]
Thanks a lot for your contribution! Only a few remarks from my side.

Did you test if this actually works? Because otherwise I could imagine that the Docker build wouldn't work just like that. I'm not entirely sure about this, but to my knowledge, the actions themselves run inside Docker containers and you can't easily run Docker inside Docker. Of course there are still ways to build a Docker image in GH actions, but they involve different steps, see https://github.com/marketplace/actions/build-and-push-docker-images.

I'd also prefer not to run the build inside Docker, but "raw" instead, i.e. using a plain Go image. Take https://github.com/muety/wakapi/blob/master/.github/workflows/linux-build-on-release.yml for inspiration and remove the unnecessary parts (running tests, uploading artifacts, ...).

**Comment by gliptak** [comment]
Thank you for your comments @muety 
Yes above I linked two runs based on PR on my fork
Certainly there is value in "raw" build and running unit test and I also see value in building/validating the Dockerfile and ` docker run mailwhale --version`. Golang build/test can be added to this initial GHA

**Comment by muety** [comment]
What benefit is there in running this build as "docker-in-docker"? I'd prefer the raw version.

**Pull request closed without merging**
